#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path(File.join(File.dirname(__FILE__), './lib/'))
$LOAD_PATH.unshift File.expand_path(File.join(File.dirname(__FILE__), '../lib/'))

require 'vsx'

def usage
  STDERR.puts "usage: #{$0} host"
  exit -1
end

hostname = ARGV[0] || 'vsx'

# usage if hostname.nil?
# usage unless hostname =~ /.*\..*/  # minimal sanity check for ip octet or name
  
begin
  vsx = Vsx.new(hostname)
  puts "Status: #{vsx.status}"
  vsx.on

  puts "Tuned to #{vsx.tuner.report}"
  puts "Volume is at #{vsx.volume.report}"
  puts "Tuner selected: #{vsx.tuner.select}"

rescue => e
  puts "oops: #{e.class}"
  puts e.message
  puts e.backtrace
end
