#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path(File.join(File.dirname(__FILE__), './lib/'))
$LOAD_PATH.unshift File.expand_path(File.join(File.dirname(__FILE__), '../lib/'))

require 'vsx'

def usage
  STDERR.puts "usage: #{$0} host"
  exit -1
end

hostname = ARGV[0] || 'vsx.sacred.net'

# usage if hostname.nil?
# usage unless hostname =~ /.*\..*/  # minimal sanity check for ip octet or name
  
begin
  vsx = Vsx.new(hostname)

  if vsx.status == :off
    vsx.on
  else
    vsx.off
  end


rescue => e
  puts "oops: #{e.class}"
end
