#!/usr/bin/env ruby


#
# mute
# unmute
# off
# on
#
# volume +, ++, +++, -, --, ---
# fm
# fm station
# am station
# computer, xbmc, xbox

# parse_command_line str
          


$LOAD_PATH.unshift File.expand_path(File.join(File.dirname(__FILE__), './lib/'))
$LOAD_PATH.unshift File.expand_path(File.join(File.dirname(__FILE__), '../lib/'))


require 'trie'

def xprompt
  STDOUT.write 'cmd> '
  STDOUT.flush
end

def xread
  line = STDIN.gets
  if line.nil?
    print '', 'goodbye'
    exit -1
  end
  return line.chomp
end

def xeval str 
  @parser.complete str
end

def xprint *texts
  STDOUT.write texts.join("\n") + "\n"
  STDOUT.flush
end


class CommandParser
  
  def initialize
    @command_set = Trie.new
    [ 'mute', 'unmute', 'off', 'on', 'volume', 'fm', 'am', 'xbmc', 'xbox' ].each do |cmd|
      @command_set[cmd.downcase] =  true # lambda { |args| dispatch cmd.to_sym, args }
    end
  end

  def complete str
    return @command_set.completions  str.downcase!
    # rescue => e
    #   STDERR.puts e
    # end
  end

end # of class


@parser = CommandParser.new

while true  
  xprompt
  xprint(xeval(xread()))
end
