#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path(File.join(File.dirname(__FILE__), './lib/'))
$LOAD_PATH.unshift File.expand_path(File.join(File.dirname(__FILE__), '../lib/'))

require 'vsx'

def usage
  STDERR.puts "usage: #{$0} host"
  exit -1
end

hostname = ARGV[0] || 'vsx.sacred.net'

# usage if hostname.nil?
# usage unless hostname =~ /.*\..*/  # minimal sanity check for ip octet or name

TARGET_VOLUME = -30

def wuft? vsx
  return (vsx.get_input_name == 'TUNER') && (vsx.volume.db >= TARGET_VOLUME) && \
  (vsx.tuner.frequency == 89.1) && (vsx.tuner.band == :fm) && (not vsx.volume.muted?)
end

  
begin
  vsx = Vsx.new(hostname)
  initial_status = vsx.status

  vsx.on

  if wuft? vsx
    puts "Already playing WUFT, exiting."
    exit
  end

  vsx.volume.db = -50
  vsx.volume.unmute

  vsx.tuner.select
  vsx.tuner.frequency = 89.1
  vsx.tuner.band = :fm
  
  sleep 5 if initial_status == :off 

  vsx.volume.fade_in(TARGET_VOLUME)
  
rescue => e
  puts "Oops: #{e.class}"
  puts e.message
  puts e.backtrace
end
