#!/usr/bin/env ruby

# I've called this script 'satya', since it switches the VSX AVR to
# the HDMI output connection from my living room Ubuntu server
# satyagraha.sacred.net - this is connected to the 'DVD' HDMI input of
# the VSX.  Of course you may not be using that name - this will just
# switch to the DVD input.


$LOAD_PATH.unshift  File.expand_path(File.dirname(__FILE__) + "/../lib")

TARGET_VOLUME = -25
STEREO = '0009'

require 'vsx'

def usage
  STDERR.puts "usage: #{$0} host"
  exit -1
end

def video1? vsx

  return (vsx.video1.selected?) && (vsx.volume.db >= TARGET_VOLUME) \
      && (not vsx.volume.muted?) && (vsx.listening_mode == STEREO)
end

hostname = ARGV[0] || 'vsx.sacred.net'

# usage if hostname.nil?
# usage unless hostname =~ /.*\..*/  # minimal sanity check for ip octet or name

begin
  vsx = Vsx.new(hostname)

  was_off = vsx.off?

  vsx.on

  if video1? vsx
    puts "Already set to VIDEO 1, exiting."
    exit
  end

  vsx.volume.db = -50
  vsx.volume.unmute
  vsx.video1.select
  vsx.listening_mode = STEREO

  sleep 5 if was_off

  vsx.volume.fade_in TARGET_VOLUME

rescue => e
  puts "Oops: #{e.class}"
  puts e.message
  puts e.backtrace
end
