#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path(File.join(File.dirname(__FILE__), './lib/'))
$LOAD_PATH.unshift File.expand_path(File.join(File.dirname(__FILE__), '../lib/'))

require 'vsx'

hostname = ARGV[0] || 'vsx.sacred.net'
  
begin
  Vsx.new(hostname).report
rescue => e
  STDERR.puts "#{e.class}: #{e.message}"
  exit -1
end
