#!/usr/bin/env ruby

$LOAD_PATH.unshift  "#{ENV['HOME']}/PersonalProjects/vsx-1021-k/lib"

require 'vsx'

hostname = ARGV[0] || 'vsx.sacred.net'

begin
  Vsx.new(hostname).report
rescue => e
  STDERR.puts "#{e.class}: #{e.message}"
  exit -1
end
