#!/usr/bin/env ruby

# I've called this script 'satya', since it switches the VSX AVR to
# the HDMI output connection from my living room Ubuntu server
# satyagraha.sacred.net - this is connected to the 'DVD' HDMI input of
# the VSX.  Of course you may not be using that name - this will just
# switch to the DVD input.

$LOAD_PATH.unshift  File.expand_path(File.dirname(__FILE__) + "/../lib")
require 'vsx'

TARGET_VOLUME = -25

def satya? vsx
  return (vsx.dvd.selected?) &&
         (vsx.volume.db >= TARGET_VOLUME) &&
         (not vsx.volume.muted?) &&
         (vsx.listening_mode == Vsx::STEREO_DIRECT_SET)
end

begin
  vsx = Vsx.new(ARGV[0] || 'vsx.sacred.net')

  was_off = vsx.off?
  vsx.on

  if satya? vsx
    puts "Already set to SATYA, exiting."
    exit
  end

  vsx.volume.db = -50
  vsx.volume.unmute
  vsx.dvd.select
  vsx.listening_mode = Vsx::STEREO_DIRECT_SET

  sleep 5 if was_off

  vsx.volume.fade_in TARGET_VOLUME

rescue => e
  puts "Oops: #{e.class}"
  puts e.message
  puts e.backtrace
end
