#!/usr/bin/env ruby

$LOAD_PATH.unshift  "#{ENV['HOME']}/PersonalProjects/vsx-1021-k/lib"

require 'vsx'

def usage
  STDERR.puts "usage: #{$0} host"
  exit -1
end

hostname = ARGV[0] || 'vsx.sacred.net'

# usage if hostname.nil?
# usage unless hostname =~ /.*\..*/  # minimal sanity check for ip octet or name

begin
  vsx = Vsx.new(hostname)

  if vsx.off?
    vsx.on
    puts 'on'
  else
    vsx.off
    puts 'off'
  end


rescue => e
  puts "#{e.class} -  #{e.message}"
  # puts e.backtrace
end
