#!/usr/bin/env ruby

$LOAD_PATH.unshift  File.expand_path(File.dirname(__FILE__) + "/../lib")

require 'vsx'

amount = ARGV[0] || -60 # 2 dB by default
hostname = ARGV[1] || 'vsx.sacred.net'

begin
  vsx = Vsx.new(hostname)
  if vsx.off?
    STDERR.puts 'VSX receiver is off, aborting'
    exit -1
  end

  vsx.volume.db=(amount.to_f)
  puts vsx.volume.report

rescue => e
  puts "Oops: #{e.class}"
  puts e.message
  puts e.backtrace
end
