#!/usr/bin/env ruby

$LOAD_PATH.unshift  "#{ENV['HOME']}/PersonalProjects/vsx-1021-k/lib"

require 'vsx'

hostname = ARGV[0] || 'vsx.sacred.net'

begin
  vsx = Vsx.new(hostname)
  if vsx.off?
    STDERR.puts 'VSX receiver is off, aborting'
    exit -1
  end

  vsx.volume.incr
  puts vsx.volume.report

rescue => e
  puts "Oops: #{e.class}"
  puts e.message
  puts e.backtrace
end
