#!/usr/bin/env ruby

$LOAD_PATH.unshift  "#{ENV['HOME']}/PersonalProjects/vsx-1021-k/lib"

require 'vsx'

amount = ARGV[0] || 2 # 2 dB by default
hostname = ARGV[1] || 'vsx.sacred.net'

begin
  vsx = Vsx.new(hostname)
  if vsx.off?
    STDERR.puts 'VSX receiver is off, aborting'
    exit -1
  end

  vsx.volume.incr amount
  puts vsx.volume.report

rescue => e
  puts "Oops: #{e.class}"
  puts e.message
  puts e.backtrace
end
