#!/usr/bin/env ruby

$LOAD_PATH.unshift  "#{ENV['HOME']}/PersonalProjects/vsx-1021-k/lib"

TARGET_VOLUME = -25
STEREO = '0009'

require 'vsx'

def usage
  STDERR.puts "usage: #{$0} host"
  exit -1
end

def xbmc? vsx
  return (vsx.input_name == 'DVD') && (vsx.volume.db >= TARGET_VOLUME) \
      && (not vsx.volume.muted?) && (vsx.listening_mode == STEREO)
end

hostname = ARGV[0] || 'vsx.sacred.net'

# usage if hostname.nil?
# usage unless hostname =~ /.*\..*/  # minimal sanity check for ip octet or name

begin
  vsx = Vsx.new(hostname)

  was_off = vsx.off?

  vsx.on

  if xbmc? vsx
    puts "Already set to XBMC, exiting."
    exit
  end

  vsx.volume.db = -50
  vsx.volume.unmute
  vsx.dvd.select
  vsx.listening_mode = STEREO

  sleep 5 if was_off

  vsx.volume.fade_in TARGET_VOLUME

rescue => e
  puts "Oops: #{e.class}"
  puts e.message
  puts e.backtrace
end
